### ISSUE TITLE
Error in Torch 2.4.1 Env, Given groups=1, weight of size [128, 4, 3, 3], expected input[1, 16, 192, 110] to have 4 channels, but got 16 channels instead

### ISSUE THREAD

**Issue by LiJT** [Ttl/ComfyUi_NNLatentUpscale#8]
!!! Exception during processing !!! Given groups=1, weight of size [128, 4, 3, 3], expected input[1, 16, 192, 110] to have 4 channels, but got 16 channels instead
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUi_NNLatentUpscale\nn_upscale.py", line 61, in upscale
    self.model(self.scale_factor * samples, scale=upscale) / self.scale_factor
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUi_NNLatentUpscale\latent_resizer.py", line 232, in forward
    x = self.conv_in(x)
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [128, 4, 3, 3], expected input[1, 16, 192, 110] to have 4 channels, but got 16 channels instead

**Comment by Ttl** [comment]
Only SD1.5 and SDXL are supported. Your image has 16 channels which is some other model.
